baseURL: https://www.0xmason.com/
languageCode: "en-us"
title: "0xMason"
theme: "github.com/Mitrichius/hugo-theme-anubis"

params:
  dateFormat: "Jan 2, 2006"
  copyCodeButton: true
  rssAsSocialIcon: true


markup:
  goldmark:
    renderer:
      unsafe: true
